language: node_js
sudo: false
branches:
  only:
  - gh-pages
env:
  global:
  - URL="http://w3c.github.io/network-error-logging/W3CTRMANIFEST"
  - DECISION="http://www.w3.org/2015/06/24-webperf-minutes.html#item01"
  - secure: "EUqgToUOjpzX+wN5d6EkNQdemQDFVgyPd1bnG2ecYwd4yXq+BBs6yaHaspSZISgAzZsXFMSaOr+wdR1P8r1hhJLedrQtXM4cW+5FasXls+oWQcaVpTS5QwjxNtR90L227m4TETNOU0bmyDtJh3T/FD/MFP3zgFZLkzMzZLTP9EM="
script:
- echo "ok"
after_success:
- '[ "${TRAVIS_PULL_REQUEST}" = "false" ] && curl "https://labs.w3.org/echidna/api/request" --data "url=$URL" --data "decision=$DECISION"
  --data "token=$TOKEN"'
